#index:
#    path: /abc
#    controller: App\Controller\DefaultController::index
api_auth_login:
  path: /api/auth/login
  methods:  [POST]

controllers:
    resource: ../src/Controller/
    type: annotation